DROP TABLE IF EXISTS MONEDA;

CREATE TABLE MONEDA
(
    ID_MONEDA      INT AUTO_INCREMENT PRIMARY KEY,
    MONEDA_ORIGEN  CHAR(3) NOT NULL,
    MONEDA_DESTINO CHAR(3) NOT NULL,
    VALOR_APLICADO FLOAT   NOT NULL,
    TIPO_CAMBIO    FLOAT   NOT NULL
);
INSERT INTO MONEDA (MONEDA_ORIGEN, MONEDA_DESTINO, VALOR_APLICADO, TIPO_CAMBIO)
values ('PEN', 'USD', '0.25', '3.99');
INSERT INTO MONEDA (MONEDA_ORIGEN, MONEDA_DESTINO, VALOR_APLICADO, TIPO_CAMBIO)
values ('USD', 'PEN','3.99' ,'0.25');